INSERT INTO localidad (id, descripcion, municipio_id) VALUES (1, 'BARRIO NUEVO GARUPA', 77);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (2, 'GARUPA', 77);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (3, 'NEMESIO PARMA', 77);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (4, 'POSADAS', 77);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (5, 'ESPERANZA', 78);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (6, 'LIBERTAD', 78);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (7, 'PUERTO IGUAZU', 78);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (8, 'VILLA COOPERATIVA', 78);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (9, 'WANDA', 78);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (10, 'ALBERDI', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (11, 'BARRIO ESCUELA 461', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (12, 'BARRIO ESCUELA 633', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (13, 'CAMPO RAMON', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (14, 'CAMPO VIERA', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (15, 'EL SALTO', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (16, 'GENERAL ALVEAR', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (17, 'GUARANI', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (18, 'LOS HELECHOS', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (19, 'OBERA', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (20, 'PANAMBI', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (21, 'PANAMBI KILOMETRO 8', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (22, 'PANAMBI KILOMETRO 15', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (23, 'SAN MARTIN', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (24, 'VILLA BONITA', 79);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (25, 'BARRIO TUNGOIL', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (26, 'COLONIA POLANA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (27, 'CORPUS', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (28, 'DOMINGO SAVIO', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (29, 'GENERAL URQUIZA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (30, 'GOBERNADOR ROCA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (31, 'HELVECIA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (32, 'HIPOLITO YRIGOYEN', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (33, 'JARDIN AMERICA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (34, 'OASIS', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (35, 'ROCA CHICA', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (36, 'SAN IGNACIO', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (37, 'SANTO PIPO', 80);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (38, 'ALBA POSSE', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (39, 'COLONIA ALICIA', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (40, 'ALICIA BAJA', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (41, 'COLONIA AURORA', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (42, 'SAN FRANCISCO DE ASIS', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (43, 'SANTA RITA', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (44, '25 DE MAYO', 81);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (45, 'FLORENTINO AMEGHINO', 82);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (46, 'ITACARUARE', 82);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (47, 'MOJON GRANDE', 82);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (48, 'SAN JAVIER', 82);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (49, 'APOSTOLES', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (50, 'AZARA', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (51, 'BARRIO RURAL', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (52, 'ESTACION APOSTOLES', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (53, 'PINDAPOY', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (54, 'RINCON DE AZARA', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (55, 'SAN JOSE', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (56, 'TRES CAPONES', 83);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (57, 'COLONIA VICTORIA', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (58, 'ELDORADO', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (59, 'MARIA MAGDALENA', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (60, 'NUEVA DELICIA', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (61, '9 DE JULIO', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (62, '9 DE JULIO KILOMETRO 20', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (63, 'PUEBLO NUEVO', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (64, 'PUERTO MADO', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (65, 'PUERTO PINARES', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (66, 'SANTIAGO DE LINIERS', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (67, 'VALLE HERMOSO', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (68, 'VILLA ROULET', 84);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (69, 'CRUCE CABALLERO', 85);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (70, 'PARAISO', 85);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (71, 'PIÑALITO SUR', 85);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (72, 'SAN PEDRO', 85);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (73, 'TOBUNA', 85);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (74, 'BARRIO CUATRO BOCAS', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (75, 'BARRIO GUATAMBU', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (76, 'BARIO ITA', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (77, 'CARAGUATAY', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (78, 'LAHARRAGUE', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (79, 'MONTECARLO', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (80, 'PIRAY KILOMETRO 18', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (81, 'PUERTO PIRAY', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (82, 'TARUMA', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (83, 'VILLA PARODI', 86);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (84, 'BARRIO DEL LAGO', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (85, 'BONPLAND', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (86, 'CANDELARIA', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (87, 'CERRO CORA', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (88, 'LORETO', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (89, 'MARTIRES', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (90, 'PROFUNDIDAD', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (91, 'PUERTO SANTA ANA', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (92, 'SANTA ANA', 87);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (93, 'ARISTOBULO DEL VALLE', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (94, 'CAMPO GRANDE', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (95, 'DOS DE MAYO NUCLEO I', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (96, 'NUCLEO I', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (97, 'NUCLEO II', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (98, 'DOS DE MAYO NUCLEO III', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (99, 'KILOMETRO 17 (RUTA 8)', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (100, '1 DE MAYO', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (101, 'PUEBLO ILLIA', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (102, 'SALTO ENCANTADO', 88);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (103, 'CAPIOVI', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (104, 'CAPIOVICIÑO', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (105, 'EL ALCAZAR', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (106, 'GARUHAPE', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (107, 'MBOPICUA', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (108, 'PUERTO LEONI', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (109, 'PUERTO RICO', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (110, 'RUIZ DE MONTOYA', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (111, 'SAN ALBERTO', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (112, 'SAN GOTARDO', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (113, 'SAN MIGUEL', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (114, 'VILLA AKERMAN', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (115, 'VILLA URRUTIA', 89);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (116, 'ALMIRANTE BROWN', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (117, 'BERNARDO DE IRIGOYEN', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (118, 'CABUREI', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (119, 'DOS HERMANAS', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (120, 'INTEGRACION', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (121, 'PIÑALITO NORTE', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (122, 'PUERTO ANDRESITO', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (123, 'PUERTO DESEADO', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (124, 'SAN ANTONIO', 90);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (125, 'EL SOBERBIO', 91);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (126, 'FRACRAN', 91);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (127, 'SAN VICENTE', 91);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (128, 'ALMAFUERTE', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (129, 'ARROYO DEL MEDIO', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (130, 'CAA - YARI', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (131, 'CERRO AZUL', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (132, 'DOS ARROYOS', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (133, 'GOBERNADOR LOPEZ', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (134, 'LEANDRO N. ALEM', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (135, 'OLEGARIO V. ANDRADE', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (136, 'VILLA LIBERTAD', 92);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (137, 'BARRA CONCEPCION', 93);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (138, 'CONCEPCION DE LA SIERRA', 93);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (139, 'LA CORITA', 93);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (140, 'SANTA MARIA', 93);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (141, 'CANDELARIA', 162);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (142, 'LEANDRO N. ALEM', 162);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (143, 'LUJAN', 162);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (144, 'QUINES', 162);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (145, 'SAN FRANCISCO DEL MONTE DE ORO', 162);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (146, 'LA CALERA', 163);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (147, 'NOGOLI', 163);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (148, 'VILLA DE LA QUEBRADA', 163);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (149, 'VILLA GENERAL ROCA', 163);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (150, 'ANCHORENA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (151, 'ARIZONA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (152, 'BAGUAL', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (153, 'BATAVIA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (154, 'BUENA ESPERANZA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (155, 'FORTIN EL PATRIA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (156, 'FORTUNA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (157, 'LA MAROMA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (158, 'LOS OVEROS', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (159, 'MARTIN DE LOYOLA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (160, 'NAHUEL MAPA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (161, 'NAVIA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (162, 'NUEVA GALIA', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (163, 'UNION', 164);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (164, 'CARPINTERIA', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (165, 'CERRO DE ORO', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (166, 'LAFINUR', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (167, 'LOS CAJONES', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (168, 'LOS MOLLES', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (169, 'MERLO', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (170, 'SANTA ROSA DEL CONLARA', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (171, 'TALITA', 165);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (172, 'CONCARAN', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (173, 'CORTADERAS', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (174, 'NASCHEL', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (175, 'PAPAGAYOS', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (176, 'RENCA', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (177, 'SAN PABLO', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (178, 'TILISARAO', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (179, 'VILLA DEL CARMEN', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (180, 'VILLA LARCA', 166);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (181, 'ALTO PELADO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (182, 'ALTO PENCOSO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (183, 'BALDE', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (184, 'BEAZLEY', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (185, 'CAZADOR', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (186, 'CHOSMES', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (187, 'DESAGUADERO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (188, 'EL VOLCAN', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (189, 'JARILLA', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (190, 'CERRO COLORADO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (191, 'CRUZ DE PIEDRA', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (192, 'EL CHORRILLO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (193, 'LAS CHACRAS', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (194, 'SAN ROQUE', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (195, 'CIUDAD DE LA PUNTA', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (196, 'MOSMOTA', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (197, 'POTRERO DE LOS FUNES', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (198, 'SALINAS DEL BEBEDERO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (199, 'SAN JERONIMO', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (200, 'SAN LUIS', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (201, 'ZANJITAS', 167);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (202, 'JUAN JORBA', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (203, 'JUAN LLERENA', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (204, 'JUSTO DARACT', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (205, 'LA PUNILLA', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (206, 'LAVAISSE', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (207, 'NACION RANQUEL', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (208, 'SAN JOSE DEL MORRO', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (209, 'VILLA MERCEDES', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (210, 'LA RIBERA', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (211, 'VILLA MERCEDES', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (212, 'VILLA REYNOLDS', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (213, 'COUNTRY CLUB LOS CALDENES', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (214, '5TA BRIGADA', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (215, 'VILLA SALLES', 168);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (216, 'LA VERTIENTE', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (217, 'LAS AGUADAS', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (218, 'LAS CHACRAS', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (219, 'LAS LAGUNAS', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (220, 'PASO GRANDE', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (221, 'POTRERILLO', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (222, 'SAN MARTIN', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (223, 'VILLA DE PRAGA', 169);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (224, 'CAROLINA', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (225, 'EL TRAPICHE', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (226, 'ESTANCIA GRANDE', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (227, 'FRAGA', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (228, 'LA BAJADA', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (229, 'LA FLORIDA', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (230, 'LA TOMA', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (231, 'RIOCITO', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (232, 'RIO GRANDE', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (233, 'SALADILLO', 170);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (234, 'BARREAL', 191);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (235, 'VILLA PITUIL', 191);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (236, 'CALINGASTA', 191);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (237, 'TAMBERIAS', 191);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (238, 'EL ENCON', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (239, 'TUPELI', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (240, 'LA CHIMBERA', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (241, 'VILLA BORJAS', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (242, 'VILLA EL TANGO', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (243, 'VILLA SANTA ROSA', 192);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (244, 'ANGUALASTO', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (245, 'BELLA VISTA', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (246, 'IGLESIA', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (247, 'LAS FLORES', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (248, 'PISMANTA', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (249, 'RODEO', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (250, 'TUDCUM', 193);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (251, 'ASTICA', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (252, 'BALDE DEL ROSARIO', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (253, 'CHUCUMA', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (254, 'LOS BALDECITOS', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (255, 'USNO', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (256, 'VILLA SAN AGUSTIN', 194);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (257, 'VILLA IBAÑEZ', 195);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (258, 'EL RINCON', 196);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (259, 'CAMPO AFUERA', 196);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (260, 'LA CAÑADA', 196);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (261, 'VILLA AMPACAMA', 196);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (262, 'VILLA GENERAL SAN MARTIN', 196);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (263, 'VILLA BASILIO NIEVAS', 197);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (264, 'VILLA TACU', 197);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (265, 'RIVADAVIA', 198);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (266, 'ALTO DE SIERRA', 199);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (267, 'COLONIA GUTIERREZ', 199);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (268, 'SANTA LUCIA', 199);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (269, 'LAS TAPIAS', 200);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (270, 'VILLA EL SALVADOR', 200);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (271, 'VILLA SEFAIR (TALACASTO)', 200);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (272, 'BERMEJO', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (273, 'BARRIO JUSTO P. CASTRO IV', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (274, 'CAUCETE', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (275, 'EL RINCON', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (276, 'LAS TALAS', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (277, 'LOS MEDANOS', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (278, 'MARAYES', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (279, 'PIE DE PALO', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (280, 'VALLECITO', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (281, 'VILLA INDEPENDENCIA', 201);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (282, 'BARRIO MUNICIPAL', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (283, 'BARRIO RUTA 40', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (284, 'CARPINTERIA', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (285, 'LAS PIEDRITAS', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (286, 'QUINTO CUARTEL', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (287, 'LA RINCONADA', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (288, 'VILLA ABERASTAIN', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (289, 'VILLA BARBOZA', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (290, 'VILLA NACUSI', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (291, 'VILLA CENTENARIO', 202);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (292, 'CAÑADA HONDA', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (293, 'CIENAGUITA', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (294, 'COLONIA FISCAL', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (295, 'DIVISADERO', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (296, 'GUANACACHE', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (297, 'LAS LAGUNAS', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (298, 'LOS BERROS', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (299, 'PEDERNAL', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (300, 'PUNTA DEL MEDANO', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (301, 'VILLA MEDIA AGUA', 203);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (302, 'SAN JUAN', 204);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (303, 'COLONIA FIORITO', 205);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (304, 'LAS CHACRITAS', 205);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (305, '9 DE JULIO', 205);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (306, 'EL MEDANITO', 206);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (307, 'RAWSON', 206);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (308, 'VILLA KRAUSE', 206);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (309, 'VILLA BOLAÑOS', 206);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (310, 'EL MEDANO', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (311, 'GRAN CHINA', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (312, 'HUACO', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (313, 'MOGNA', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (314, 'NIQUIVIL', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (315, 'EL FISCAL', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (316, 'LA FALDA', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (317, 'PAMPA VIEJA', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (318, 'SAN ISIDRO', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (319, 'SAN JOSE DE JACHAL', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (320, 'TAMBERIAS', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (321, 'VILLA MALVINAS ARGENTINAS', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (322, 'VILLA MERCEDES', 207);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (323, 'BARRIO SADOP', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (324, 'DOS ACEQUIAS', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (325, 'SAN ISIDRO', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (326, 'VILLA EL SALVADOR', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (327, 'VILLA DOMINGUITO', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (328, 'VILLA DON BOSCO', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (329, 'VILLA SAN MARTIN', 208);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (330, 'CHIMBAS', 209);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (331, 'EL MOGOTE', 209);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (332, 'VILLA PAULA ALBARRACIN', 209);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (333, 'ESTACION RAICES', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (334, 'INGENIERO MIGUEL SAJAROFF', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (335, 'JUBILEO', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (336, 'PASO DE LA LAGUNA', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (337, 'VILLA CLARA', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (338, 'VILLA DOMINGUEZ', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (339, 'VILLAGUAY', 211);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (340, 'GENERAL CAMPOS', 212);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (341, 'SAN SALVADOR', 212);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (342, 'ARANGUREN', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (343, 'BETBEDER', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (344, 'DON CRISTOBAL', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (345, 'FEBRE', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (346, 'HERNANDEZ', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (347, 'LUCAS GONZALEZ', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (348, 'NOGOYA', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (349, 'XX DE SETIEMBRE', 213);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (350, 'ALTAMIRANO SUR', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (351, 'DURAZNO', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (352, 'ESTACION ARROYO CLE', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (353, 'GOBERNADOR ECHAGUE', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (354, 'GOBERNADOR MANSILLA', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (355, 'GOBERNADOR SOLA', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (356, 'GUARDAMONTE', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (357, 'LAS GUACHAS', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (358, 'MACIA', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (359, 'ROSARIO DEL TALA', 214);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (360, 'ALCARAZ', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (361, 'BOVRIL', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (362, 'COLONIA AVIGDOR', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (363, 'EL SOLAR', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (364, 'LA PAZ', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (365, 'PIEDRAS BLANCAS', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (366, 'SAN GUSTAVO', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (367, 'SANTA ELENA', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (368, 'SIR LEONARD', 215);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (369, 'CALABACILLA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (370, 'CLODOMIRO LEDESMA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (371, 'COLONIA AYUI', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (372, 'COLONIA GENERAL ROCA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (373, 'BENITO LEGEREN', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (374, 'CONCORDIA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (375, 'LAS TEJAS', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (376, 'VILLA ADELA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (377, 'VILLA ZORRAQUIN', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (378, 'ESTACION YERUA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (379, 'ESTACION YUQUERI', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (380, 'ESTANCIA GRANDE', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (381, 'LA CRIOLLA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (382, 'LOS CHARRUAS', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (383, 'NUEVA ESCOCIA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (384, 'PEDERNAL', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (385, 'PUERTO YERUA', 216);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (386, 'CONSCRIPTO BERNARDI', 217);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (387, 'EL CIMARRON', 217);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (388, 'FEDERAL', 217);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (389, 'NUEVA VIZCAYA', 217);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (390, 'SAUCE DE LUNA', 217);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (391, 'ALDEA SAN ANTONIO', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (392, 'ALDEA SAN JUAN', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (393, 'ENRIQUE CARBO', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (394, 'ESTACION ESCRIÑA', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (395, 'FAUSTINO M. PARERA', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (396, 'GENERAL ALMADA', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (397, 'GILBERT', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (398, 'GUALEGUAYCHU', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (399, 'IRAZUSTA', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (400, 'LARROQUE', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (401, 'PASTOR BRITOS', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (402, 'PUEBLO GENERAL BELGRANO', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (403, 'URDINARRAIN', 218);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (404, 'CEIBAS', 219);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (405, 'IBICUY', 219);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (406, 'MEDANOS', 219);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (407, 'VILLA PARANACITO', 219);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (408, 'ANTELO', 220);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (409, 'MOLINO DOLL', 220);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (410, 'VICTORIA', 220);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (411, 'ALDEA BRASILERA', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (412, 'ALDEA GRAPSCHENTAL', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (413, 'ALDEA PROTESTANTE', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (414, 'ALDEA SALTO', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (415, 'ALDEA SAN FRANCISCO', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (416, 'ALDEA SPATZENKUTTER', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (417, 'ALDEA VALLE MARIA', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (418, 'COLONIA ENSAYO', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (419, 'DIAMANTE', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (420, 'STROBEL', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (421, 'ESTACION CAMPS', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (422, 'GENERAL ALVEAR', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (423, 'GENERAL RACEDO', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (424, 'GENERAL RAMIREZ', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (425, 'LA JUANITA', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (426, 'LA JAULA', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (427, 'PARAJE LA VIRGEN', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (428, 'PUERTO LAS CUEVAS', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (429, 'ESTACION PUIGGARI', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (430, 'VILLA LIBERTADOR SAN MARTIN', 221);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (431, 'BASAVILBASO', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (432, 'CASEROS', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (433, 'COLONIA ELIA', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (434, 'CONCEPCION DEL URUGUAY', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (435, 'HERRERA', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (436, 'LAS MOSCAS', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (437, 'LIBAROS', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (438, '1 DE MAYO', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (439, 'PRONUNCIAMIENTO', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (440, 'ROCAMORA', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (441, 'SANTA ANITA', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (442, 'VILLA MANTERO', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (443, 'VILLA SAN JUSTO', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (444, 'VILLA SAN MARCIAL', 222);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (445, 'ALDEA MARIA LUISA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (446, 'ALDEA SAN JUAN', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (447, 'ALDEA SAN RAFAEL', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (448, 'ALDEA SANTA MARIA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (449, 'ALDEA SANTA ROSA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (450, 'CERRITO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (451, 'PUEBLO MORENO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (452, 'COLONIA AVELLANEDA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (453, 'COLONIA CRESPO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (454, 'CRESPO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (455, 'EL PALENQUE', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (456, 'EL PINGO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (457, 'EL RAMBLON', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (458, 'HASENKAMP', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (459, 'HERNANDARIAS', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (460, 'LA PICADA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (461, 'LAS TUNAS', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (462, 'MARIA GRANDE', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (463, 'ORO VERDE', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (464, 'PARANA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (465, 'PUEBLO BELLOCQ', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (466, 'PUEBLO BRUGO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (467, 'PUEBLO GENERAL SAN MARTIN', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (468, 'SAN BENITO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (469, 'SAUCE MONTRULL', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (470, 'SAUCE PINTO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (471, 'SEGUI', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (472, 'SOSA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (473, 'TABOSSI', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (474, 'TEZANOS PINTO', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (475, 'VIALE', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (476, 'VILLA FONTANA', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (477, 'VILLA GOBERNADOR LUIS F. ETCHEVEHERE', 223);
INSERT INTO localidad (id, descripcion, municipio_id) VALUES (478, 'VILLA URQUIZA', 223);
