INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(2, 'MUNICIPIO', 'Apóstoles', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(3, 'MUNICIPIO', 'Tres Capones', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(4, 'MUNICIPIO', 'Mártires', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(5, 'MUNICIPIO', 'Santiago de Liniers', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(6, 'MUNICIPIO', 'San Pedro', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(7, 'MUNICIPIO', 'Campo Grande', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(8, 'MUNICIPIO', 'Puerto Rico', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(9, 'MUNICIPIO', 'Montecarlo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(10, 'MUNICIPIO', 'El Soberbio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(11, 'MUNICIPIO', 'Cerro Corá', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(12, 'MUNICIPIO', 'Garupá', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(13, 'MUNICIPIO', 'Santa Ana', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(14, 'MUNICIPIO', 'Corpus', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(15, 'MUNICIPIO', 'Gobernador Roca', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(16, 'MUNICIPIO', 'Posadas', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(17, 'MUNICIPIO', 'Panambí', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(18, 'MUNICIPIO', 'Hipólito Irigoyen', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(19, 'MUNICIPIO', 'Profundidad', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(20, 'MUNICIPIO', 'Azara', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(21, 'MUNICIPIO', 'Colonia Aurora', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(22, 'MUNICIPIO', 'Fachinal', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(23, 'MUNICIPIO', 'El Alcázar', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(24, 'MUNICIPIO', 'Capioví', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(25, 'MUNICIPIO', 'Santo Pipo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(26, 'MUNICIPIO', 'Colonia Polana', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(27, 'MUNICIPIO', 'Gobernador López', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(28, 'MUNICIPIO', 'Jardín América', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(29, 'MUNICIPIO', 'Caa Yarí', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(30, 'MUNICIPIO', 'Olegario V. Andrade', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(31, 'MUNICIPIO', 'Cerro Azul', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(32, 'MUNICIPIO', 'General J. J. Urquiza', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(33, 'MUNICIPIO', 'Alba Posse', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(34, 'MUNICIPIO', 'Los Helechos', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(35, 'MUNICIPIO', 'San Vicente', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(36, 'MUNICIPIO', 'Mojón Grande', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(37, 'MUNICIPIO', 'Gral. Alvear', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(38, 'MUNICIPIO', 'San Javier', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(39, 'MUNICIPIO', 'Ruiz de Montoya', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(40, 'MUNICIPIO', 'Santa María', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(41, 'MUNICIPIO', 'Guaraní', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(42, 'MUNICIPIO', 'San Martín', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(43, 'MUNICIPIO', 'San José', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(44, 'MUNICIPIO', 'Puerto Esperanza', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(45, 'MUNICIPIO', 'Itacaruaré', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(46, 'MUNICIPIO', 'Almafuerte', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(47, 'MUNICIPIO', 'Colonia Alberdi', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(48, 'MUNICIPIO', 'Leandro N. Alem', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(49, 'MUNICIPIO', 'Colonia Delicia', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(50, 'MUNICIPIO', 'Bernardo de Irigoyen', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(51, 'MUNICIPIO', 'Colonia Victoria', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(52, 'MUNICIPIO', '25 de Mayo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(53, 'MUNICIPIO', 'Oberá', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(54, 'MUNICIPIO', 'Iguazú', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(55, 'MUNICIPIO', 'Leoni', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(56, 'MUNICIPIO', 'Caraguatay', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(57, 'MUNICIPIO', 'Campo Viera', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(58, 'MUNICIPIO', 'Dos Arroyos', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(59, 'MUNICIPIO', 'Concepción de la Sierra', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(60, 'MUNICIPIO', 'Arroyo del Medio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(61, 'MUNICIPIO', '9 de Julio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(62, 'MUNICIPIO', 'Bonpland', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(63, 'MUNICIPIO', 'San Ignacio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(64, 'MUNICIPIO', 'Comandante A. Guacurary', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(65, 'MUNICIPIO', 'San Antonio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(66, 'MUNICIPIO', 'Aristóbulo del Valle', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(67, 'MUNICIPIO', 'Ameghino', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(68, 'MUNICIPIO', 'Campo Ramón', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(69, 'MUNICIPIO', 'Eldorado', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(70, 'MUNICIPIO', 'Puerto Piray', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(71, 'MUNICIPIO', 'Garuhapé', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(72, 'MUNICIPIO', 'Colonia Wanda', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(73, 'MUNICIPIO', 'Dos de Mayo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(74, 'MUNICIPIO', 'Candelaria', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(75, 'MUNICIPIO', 'Loreto', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(76, 'MUNICIPIO', 'Libertad', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(77, 'MUNICIPIO', 'Capital', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(78, 'MUNICIPIO', 'Iguazú', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(79, 'MUNICIPIO', 'Oberá', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(80, 'MUNICIPIO', 'San Ignacio', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(81, 'MUNICIPIO', '25 de Mayo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(82, 'MUNICIPIO', 'San Javier', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(83, 'MUNICIPIO', 'Apóstoles', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(84, 'MUNICIPIO', 'Eldorado', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(85, 'MUNICIPIO', 'San Pedro', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(86, 'MUNICIPIO', 'Montecarlo', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(87, 'MUNICIPIO', 'Candelaria', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(88, 'MUNICIPIO', 'Cainguás', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(89, 'MUNICIPIO', 'Libertador General San Martín', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(90, 'MUNICIPIO', 'General Manuel Belgrano', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(91, 'MUNICIPIO', 'Guaraní', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(92, 'MUNICIPIO', 'Leandro N. Alem', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(93, 'MUNICIPIO', 'Concepción', 1);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(95, 'MUNICIPIO', 'Zanjitas', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(96, 'MUNICIPIO', 'Beazley', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(97, 'MUNICIPIO', 'Balde', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(98, 'MUNICIPIO', 'Fraga', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(99, 'MUNICIPIO', 'P. de los Funes', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(100, 'MUNICIPIO', 'Carolina', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(101, 'MUNICIPIO', 'San Francisco', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(102, 'MUNICIPIO', 'Merlo', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(103, 'MUNICIPIO', 'Juana Koslay', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(104, 'MUNICIPIO', 'Batavia', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(105, 'MUNICIPIO', 'Ranqueles', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(106, 'MUNICIPIO', 'Alto Pencoso', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(107, 'MUNICIPIO', 'Las Aguadas', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(108, 'MUNICIPIO', 'San Martin', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(109, 'MUNICIPIO', 'Leandro N. Alem', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(110, 'MUNICIPIO', 'La Calera', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(111, 'MUNICIPIO', 'La Punilla', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(112, 'MUNICIPIO', 'Fortin el Patria', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(113, 'MUNICIPIO', 'Lujan', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(114, 'MUNICIPIO', 'Quines', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(115, 'MUNICIPIO', 'Las Vertientes', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(116, 'MUNICIPIO', 'Paso Grande', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(117, 'MUNICIPIO', 'San Luis', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(118, 'MUNICIPIO', 'El Trapiche', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(119, 'MUNICIPIO', 'Navia', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(120, 'MUNICIPIO', 'Desaguadero', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(121, 'MUNICIPIO', 'Villa Mercedes', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(122, 'MUNICIPIO', 'Candelaria', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(123, 'MUNICIPIO', 'Alto Pelado', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(124, 'MUNICIPIO', 'Las Lagunas', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(125, 'MUNICIPIO', 'Las Chacras', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(126, 'MUNICIPIO', 'V, de Praga', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(127, 'MUNICIPIO', 'Villa del Carmen', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(128, 'MUNICIPIO', 'San Pablo', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(129, 'MUNICIPIO', 'Renca', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(130, 'MUNICIPIO', 'Tilisarao', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(131, 'MUNICIPIO', 'Los Molles', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(132, 'MUNICIPIO', 'V, Gral, Roca', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(133, 'MUNICIPIO', 'V, de la Quebrada', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(134, 'MUNICIPIO', 'Nogoli', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(135, 'MUNICIPIO', 'Carpinteria', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(136, 'MUNICIPIO', 'La Toma', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(137, 'MUNICIPIO', 'Juan Llerena', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(138, 'MUNICIPIO', 'Concaran', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(139, 'MUNICIPIO', 'Talita', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(140, 'MUNICIPIO', 'Sta Rosa del Conlara', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(141, 'MUNICIPIO', 'Villa Larca', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(142, 'MUNICIPIO', 'Papagayos', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(143, 'MUNICIPIO', 'Naschel', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(144, 'MUNICIPIO', 'Justo Daract', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(145, 'MUNICIPIO', 'Saladillo', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(146, 'MUNICIPIO', 'Bagual', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(147, 'MUNICIPIO', 'Arizona', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(148, 'MUNICIPIO', 'Buena Esperanza', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(149, 'MUNICIPIO', 'Union', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(150, 'MUNICIPIO', 'San Jeronimo', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(151, 'MUNICIPIO', 'El Volcan', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(152, 'MUNICIPIO', 'Estancia Grande', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(153, 'MUNICIPIO', 'La Punta', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(154, 'MUNICIPIO', 'Nueva Galia', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(155, 'MUNICIPIO', 'Fortuna', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(156, 'MUNICIPIO', 'Anchorena', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(157, 'MUNICIPIO', 'Juan Jorba', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(158, 'MUNICIPIO', 'Lavaisse', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(159, 'MUNICIPIO', 'San Jose del Morro', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(160, 'MUNICIPIO', 'Cortaderas', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(161, 'MUNICIPIO', 'Lafinur', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(162, 'MUNICIPIO', 'Ayacucho', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(163, 'MUNICIPIO', 'Belgrano', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(164, 'MUNICIPIO', 'Gobernador Dupuy', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(165, 'MUNICIPIO', 'Junín', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(166, 'MUNICIPIO', 'Chacabuco', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(167, 'MUNICIPIO', 'Juan Martín de Pueyrredón', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(168, 'MUNICIPIO', 'General Pedernera', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(169, 'MUNICIPIO', 'Libertador General San Martín', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(170, 'MUNICIPIO', 'Coronel Pringles', 94);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(172, 'MUNICIPIO', 'Iglesia', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(173, 'MUNICIPIO', 'Valle Fértil', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(174, 'MUNICIPIO', 'Ullum', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(175, 'MUNICIPIO', 'Albardón', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(176, 'MUNICIPIO', 'Zonda', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(177, 'MUNICIPIO', 'Chimbas', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(178, 'MUNICIPIO', 'Rivadavia', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(179, 'MUNICIPIO', 'Santa Lucía', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(180, 'MUNICIPIO', 'Rawson', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(181, 'MUNICIPIO', 'Pocito', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(182, 'MUNICIPIO', 'Sarmiento', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(183, 'MUNICIPIO', 'Jáchal', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(184, 'MUNICIPIO', 'Calingasta', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(185, 'MUNICIPIO', '25 de Mayo', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(186, 'MUNICIPIO', 'San Juan', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(187, 'MUNICIPIO', '9 de Julio', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(188, 'MUNICIPIO', 'San Martín', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(189, 'MUNICIPIO', 'Angaco', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(190, 'MUNICIPIO', 'Caucete', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(191, 'MUNICIPIO', 'Calingasta', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(192, 'MUNICIPIO', '25 de Mayo', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(193, 'MUNICIPIO', 'Iglesia', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(194, 'MUNICIPIO', 'Valle Fértil', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(195, 'MUNICIPIO', 'Ullum', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(196, 'MUNICIPIO', 'Albardón', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(197, 'MUNICIPIO', 'Zonda', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(198, 'MUNICIPIO', 'Rivadavia', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(199, 'MUNICIPIO', 'Santa Lucía', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(200, 'MUNICIPIO', 'Angaco', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(201, 'MUNICIPIO', 'Caucete', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(202, 'MUNICIPIO', 'Pocito', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(203, 'MUNICIPIO', 'Sarmiento', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(204, 'MUNICIPIO', 'Capital', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(205, 'MUNICIPIO', '9 de Julio', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(206, 'MUNICIPIO', 'Rawson', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(207, 'MUNICIPIO', 'Jáchal', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(208, 'MUNICIPIO', 'San Martín', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(209, 'MUNICIPIO', 'Chimbas', 171);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(211, 'MUNICIPIO', 'Villaguay', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(212, 'MUNICIPIO', 'San Salvador', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(213, 'MUNICIPIO', 'Nogoyá', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(214, 'MUNICIPIO', 'Tala', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(215, 'MUNICIPIO', 'La Paz', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(216, 'MUNICIPIO', 'Concordia', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(217, 'MUNICIPIO', 'Federal', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(218, 'MUNICIPIO', 'Gualeguaychú', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(219, 'MUNICIPIO', 'Islas del Ibicuy', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(220, 'MUNICIPIO', 'Victoria', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(221, 'MUNICIPIO', 'Diamante', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(222, 'MUNICIPIO', 'Uruguay', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(223, 'MUNICIPIO', 'Paraná', 210);
INSERT INTO sector (id, tipo, descripcion, provincia_id) VALUES(224, 'MUNICIPIO', 'Colón', 210);
