INSERT INTO sector (id, tipo, descripcion ) VALUES (1, 'PROVINCIA', 'Misiones');
INSERT INTO sector (id, tipo, descripcion ) VALUES (94, 'PROVINCIA', 'San Luis');
INSERT INTO sector (id, tipo, descripcion ) VALUES (171, 'PROVINCIA', 'San Juan');
INSERT INTO sector (id, tipo, descripcion ) VALUES (210, 'PROVINCIA', 'Entre Ríos');
INSERT INTO sector (id, tipo, descripcion ) VALUES (228, 'PROVINCIA', 'Santa Cruz');
INSERT INTO sector (id, tipo, descripcion ) VALUES (236, 'PROVINCIA', 'Río Negro');
INSERT INTO sector (id, tipo, descripcion ) VALUES (320, 'PROVINCIA', 'Chubut');
INSERT INTO sector (id, tipo, descripcion ) VALUES (382, 'PROVINCIA', 'Córdoba');
INSERT INTO sector (id, tipo, descripcion ) VALUES (509, 'PROVINCIA', 'Mendoza');
INSERT INTO sector (id, tipo, descripcion ) VALUES (546, 'PROVINCIA', 'La Rioja');
INSERT INTO sector (id, tipo, descripcion ) VALUES (583, 'PROVINCIA', 'Catamarca');
INSERT INTO sector (id, tipo, descripcion ) VALUES (636, 'PROVINCIA', 'La Pampa');
INSERT INTO sector (id, tipo, descripcion ) VALUES (739, 'PROVINCIA', 'Santiago del Estero');
INSERT INTO sector (id, tipo, descripcion ) VALUES (767, 'PROVINCIA', 'Corrientes');
INSERT INTO sector (id, tipo, descripcion ) VALUES (862, 'PROVINCIA', 'Santa Fe');
INSERT INTO sector (id, tipo, descripcion ) VALUES (982, 'PROVINCIA', 'Tucumán');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1100, 'PROVINCIA', 'Neuquén');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1174, 'PROVINCIA', 'Salta');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1257, 'PROVINCIA', 'Chaco');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1351, 'PROVINCIA', 'Formosa');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1398, 'PROVINCIA', 'Jujuy');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1475, 'PROVINCIA', 'Ciudad Autónoma de Buenos Aires');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1491, 'PROVINCIA', 'Buenos Aires');
INSERT INTO sector (id, tipo, descripcion ) VALUES (1692, 'PROVINCIA', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur');
