INSERT INTO sector (id, tipo, descripcion ) VALUES (1, 'PROVINCIA', 'BUENOS AIRES');
INSERT INTO sector (id, tipo, descripcion ) VALUES (52, 'PROVINCIA', 'CATAMARCA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (70, 'PROVINCIA', 'CHACO');
INSERT INTO sector (id, tipo, descripcion ) VALUES (97, 'PROVINCIA', 'CHUBUT');
INSERT INTO sector (id, tipo, descripcion ) VALUES (114, 'PROVINCIA', 'CORDOBA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (142, 'PROVINCIA', 'CORRIENTES');
INSERT INTO sector (id, tipo, descripcion ) VALUES (169, 'PROVINCIA', 'CIUDAD DE BUENOS AIRES');
INSERT INTO sector (id, tipo, descripcion ) VALUES (172, 'PROVINCIA', 'ENTRE RIOS');
INSERT INTO sector (id, tipo, descripcion ) VALUES (191, 'PROVINCIA', 'FORMOSA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (202, 'PROVINCIA', 'JUJUY');
INSERT INTO sector (id, tipo, descripcion ) VALUES (220, 'PROVINCIA', 'LA PAMPA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (244, 'PROVINCIA', 'LA RIOJA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (264, 'PROVINCIA', 'MENDOZA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (284, 'PROVINCIA', 'MISIONES');
INSERT INTO sector (id, tipo, descripcion ) VALUES (303, 'PROVINCIA', 'NEUQUEN');
INSERT INTO sector (id, tipo, descripcion ) VALUES (321, 'PROVINCIA', 'RIO NEGRO');
INSERT INTO sector (id, tipo, descripcion ) VALUES (336, 'PROVINCIA', 'SALTA');
INSERT INTO sector (id, tipo, descripcion ) VALUES (361, 'PROVINCIA', 'SAN JUAN');
INSERT INTO sector (id, tipo, descripcion ) VALUES (382, 'PROVINCIA', 'SAN LUIS');
INSERT INTO sector (id, tipo, descripcion ) VALUES (393, 'PROVINCIA', 'SANTA CRUZ');
INSERT INTO sector (id, tipo, descripcion ) VALUES (402, 'PROVINCIA', 'SANTA FE');
INSERT INTO sector (id, tipo, descripcion ) VALUES (423, 'PROVINCIA', 'SANTIAGO DEL ESTERO');
INSERT INTO sector (id, tipo, descripcion ) VALUES (452, 'PROVINCIA', 'TIERRA DEL FUEGO');
INSERT INTO sector (id, tipo, descripcion ) VALUES (458, 'PROVINCIA', 'TUCUMAN');
